### PR TITLE
Added a new section

### PR DESCRIPTION
**Pull request by ericdevelops**
Resolve JIRA-259

Decided to add new fucntion because bla bla bla.

### CODE REVIEW

**Review by michaelsbach — APPROVED** [review]
great job!

**Review by 19D — APPROVED** [review]

**Review by EOlvera22 — APPROVED** [review]

**Review by wright-at-will — APPROVED** [review]

**Review by JaredAndrz — APPROVED** [review]
Good Job

**Review by Calebhowe22 — APPROVED** [review]
This looks like a great slice of code.

**Comment by ericruiz-developer** [comment]
> great job!

Hey thanks man, you'll never write code like this.

**Review by xConde — APPROVED** [review]

**Pull request merged**
